version: "3.9"
services:
  db:
    image: postgres
    container_name: Teste
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/data/postgresql

volumes:
  postgres_data:
    driver: local